%get subject structure
function [sub] = pm_data_no15

%%Anosmic subject
sub(1).name='merry_calf';
sub(1).gr='AC';
sub(2).name='romantic_panda';
sub(2).gr='AC';
sub(3).name='unbiased_barnacle';
sub(3).gr='AC';
sub(4).name='cunning_ferret'; 
sub(4).gr='AC';
sub(5).name='willing_unicorn';
sub(5).gr='AC';
sub(6).name='amusing_gator';
sub(6).gr='AC';
sub(7).name='living_drake';
sub(7).gr='AC';
sub(8).name='profound_rat';
sub(8).gr='AC'
sub(9).name='trusting_turtle'; 
sub(9).gr='AC'
sub(10).name='darling_gryphon';
sub(10).gr='AC'
sub(11).name='settled_coral'; 
sub(11).gr='AC'
sub(12).name='aware_jaguar'; 
sub(12).gr='AC'
sub(13).name='easy_man';
sub(13).gr='AC'
sub(14).name='possible_macaw'; 
sub(14).gr='AC'
% sub(15).name='winning_moose'; 
% sub(15).gr='AC'
sub(15).name='unique_airedale';
sub(15).gr='AC'
sub(16).name='intimate_beetle';
sub(16).gr='AC'
sub(17).name='casual_leopard';
sub(17).gr='AC'
sub(18).name='up_dinosaur'; 
sub(18).gr='AC'
sub(19).name='content_narwhal';
sub(19).gr='AC'

%Control subjects
%get subject structure
sub(20).name='sweeping_chimp';
sub(20).gr='CS';
sub(21).name='nice_tiger';
sub(21).gr='CS';
sub(22).name='steady_liger';
sub(22).gr='CS';
sub(23).name='poetic_roughy'; 
sub(23).gr='CS';
sub(24).name='flowing_mullet';
sub(24).gr='CS';
sub(25).name='light_shad';
sub(25).gr='CS';
sub(26).name='knowing_skylark';
sub(26).gr='CS';
sub(27).name='emerging_reindeer';
sub(27).gr='CS'
sub(28).name='select_penguin'; 
sub(28).gr='CS'
sub(29).name='exact_joey';
sub(29).gr='CS'
sub(30).name='stirred_shepherd'; 
sub(30).gr='CS'
sub(31).name='just_seagull'; 
sub(31).gr='CS'
sub(32).name='above_midge';
sub(32).gr='CS'
sub(33).name='pleased_chigger'; 
sub(33).gr='CS'
sub(34).name='many_tetra'; 
sub(34).gr='CS'
sub(35).name='electric_blowfish';
sub(35).gr='CS'
sub(36).name='witty_hound';
sub(36).gr='CS'
sub(37).name='polished_jaguar';
sub(37).gr='CS'
sub(38).name='dynamic_goat'; 
sub(38).gr='CS'
sub(39).name='sweet_mudfish';
sub(39).gr='CS'
end