%get subject structure
function [sub] = pm_data_no15

%%Anosmic subject
sub(1).name='merry_calf';
sub(1).gr='AC';
sub(2).name='romantic_panda';
sub(2).gr='AC';
sub(3).name='unbiased_barnacle';
sub(3).gr='AC';
% sub(4).name='cunning_ferret'; 
% sub(4).gr='AC'; %doesn't know incens
sub(4).name='willing_unicorn';
sub(4).gr='AC';
sub(5).name='amusing_gator';
sub(5).gr='AC';
sub(6).name='living_drake';
sub(6).gr='AC';
sub(7).name='profound_rat';
sub(7).gr='AC'
sub(8).name='trusting_turtle'; 
sub(8).gr='AC'
% sub(10).name='darling_gryphon';
% sub(10).gr='AC' %doesn't know incens
sub(9).name='settled_coral'; 
sub(9).gr='AC'
sub(10).name='aware_jaguar'; 
sub(10).gr='AC'
sub(11).name='easy_man';
sub(11).gr='AC'
sub(12).name='possible_macaw'; 
sub(12).gr='AC'
% sub(15).name='winning_moose'; 
% sub(15).gr='AC' %put all low values
sub(13).name='unique_airedale';
sub(13).gr='AC'
sub(14).name='intimate_beetle';
sub(14).gr='AC'
sub(15).name='casual_leopard';
sub(15).gr='AC'
sub(16).name='up_dinosaur'; 
sub(16).gr='AC'
sub(17).name='content_narwhal';
sub(17).gr='AC'

%Control subjects
%get subject structure
sub(18).name='sweeping_chimp';
sub(18).gr='CS';
sub(19).name='nice_tiger';
sub(19).gr='CS';
sub(20).name='steady_liger';
sub(20).gr='CS';
sub(21).name='poetic_roughy'; 
sub(21).gr='CS';
sub(22).name='flowing_mullet';
sub(22).gr='CS';
sub(23).name='light_shad';
sub(23).gr='CS';
sub(24).name='knowing_skylark';
sub(24).gr='CS';
sub(25).name='emerging_reindeer';
sub(25).gr='CS'
sub(26).name='select_penguin'; 
sub(26).gr='CS'
sub(27).name='exact_joey';
sub(27).gr='CS'
sub(28).name='stirred_shepherd'; 
sub(28).gr='CS'
sub(29).name='just_seagull'; 
sub(29).gr='CS'
sub(30).name='above_midge';
sub(30).gr='CS'
sub(31).name='pleased_chigger'; 
sub(31).gr='CS'
sub(32).name='many_tetra'; 
sub(32).gr='CS'
sub(33).name='electric_blowfish';
sub(33).gr='CS'
sub(34).name='witty_hound';
sub(34).gr='CS'
sub(35).name='polished_jaguar';
sub(35).gr='CS'
sub(36).name='dynamic_goat'; 
sub(36).gr='CS'
sub(37).name='sweet_mudfish';
sub(37).gr='CS'
end